name: deploy main branch to production
on:
  push:
    branches:
      - main
jobs:
  Deploy-To-GCP:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Connect to remote and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ vars.GCP_EXTERNAL_IP }}
        username: ${{ vars.GCP_USERNAME }}
        key: ${{ secrets.GCP_PRIVATE_KEY }}
        port: 22
        command_timeout: 30m
        script: | 
          cd chillbot
          git pull
          echo "${{ secrets.PROD_ENV }}" > .env
          docker compose up --build -d