name: deploy main branch to production
on:
  push:
    branches:
      - main
jobs:
  Deploy-To-GCP:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ secrets.GCP_PRIVATE_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H ${{ vars.GCP_EXTERNAL_IP }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no ${{ vars.GCP_USERNAME }}@${{ vars.GCP_EXTERNAL_IP }}
          ssh -i ~/.ssh/key.pem ${{ vars.GCP_USERNAME }}@${{ vars.GCP_EXTERNAL_IP }} "cd chillbot; git pull; echo "${{ secrets.PROD_ENV }}" > .env; "docker compose up --build -d"